package meeting

import (
	"github.com/OpenSlides/openslides-backend-service/internal/action"
	"github.com/OpenSlides/openslides-backend-service/internal/model"
	"github.com/OpenSlides/openslides-go/perm"
)

func init() {
	a := action.NewUpdateAction("meeting.update", model.MustGet("meeting"))
	a.Permission = perm.MeetingCanManageSettings

	a.Schema = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"id":                          map[string]any{"type": "integer"},
			"name":                        map[string]any{"type": "string"},
			"description":                 map[string]any{"type": "string"},
			"location":                    map[string]any{"type": "string"},
			"start_time":                  map[string]any{"type": "integer"},
			"end_time":                    map[string]any{"type": "integer"},
			"welcome_title":               map[string]any{"type": "string"},
			"welcome_text":                map[string]any{"type": "string"},
			"enable_anonymous":            map[string]any{"type": "boolean"},
			"custom_translations":         map[string]any{"type": "object"},
			"conference_show":             map[string]any{"type": "boolean"},
			"conference_auto_connect":     map[string]any{"type": "boolean"},
			"conference_los_restriction":  map[string]any{"type": "boolean"},
			"conference_stream_url":       map[string]any{"type": "string"},
			"conference_stream_poster_url": map[string]any{"type": "string"},
			"conference_open_microphone":  map[string]any{"type": "boolean"},
			"conference_open_video":       map[string]any{"type": "boolean"},
			"conference_auto_connect_next_speakers": map[string]any{"type": "integer"},
			"conference_enable_helpdesk":  map[string]any{"type": "boolean"},
			"applause_enable":             map[string]any{"type": "boolean"},
			"applause_type":               map[string]any{"type": "string"},
			"applause_show_level":         map[string]any{"type": "boolean"},
			"applause_min_amount":         map[string]any{"type": "integer"},
			"applause_max_amount":         map[string]any{"type": "integer"},
			"applause_timeout":            map[string]any{"type": "integer"},
			"applause_particle_image_url": map[string]any{"type": "string"},
			"projector_countdown_default_time":      map[string]any{"type": "integer"},
			"projector_countdown_warning_time":      map[string]any{"type": "integer"},
			"export_csv_encoding":         map[string]any{"type": "string"},
			"export_csv_separator":        map[string]any{"type": "string"},
			"export_pdf_pagenumber_alignment": map[string]any{"type": "string"},
			"export_pdf_fontsize":         map[string]any{"type": "integer"},
			"export_pdf_pagesize":         map[string]any{"type": "string"},
			"export_pdf_line_height":      map[string]any{"type": "number"},
			"export_pdf_page_margin_left": map[string]any{"type": "integer"},
			"export_pdf_page_margin_top":  map[string]any{"type": "integer"},
			"export_pdf_page_margin_right":  map[string]any{"type": "integer"},
			"export_pdf_page_margin_bottom": map[string]any{"type": "integer"},
			"agenda_show_subtitles":              map[string]any{"type": "boolean"},
			"agenda_enable_numbering":            map[string]any{"type": "boolean"},
			"agenda_number_prefix":               map[string]any{"type": "string"},
			"agenda_numeral_system":              map[string]any{"type": "string"},
			"agenda_item_creation":               map[string]any{"type": "string"},
			"agenda_new_items_default_visibility": map[string]any{"type": "string"},
			"list_of_speakers_amount_last_on_projector":            map[string]any{"type": "integer"},
			"list_of_speakers_amount_next_on_projector":            map[string]any{"type": "integer"},
			"list_of_speakers_couple_countdown":                    map[string]any{"type": "boolean"},
			"list_of_speakers_show_amount_of_speakers_on_slide":    map[string]any{"type": "boolean"},
			"list_of_speakers_present_users_only":                  map[string]any{"type": "boolean"},
			"list_of_speakers_show_first_contribution":             map[string]any{"type": "boolean"},
			"list_of_speakers_enable_point_of_order_speakers":      map[string]any{"type": "boolean"},
			"list_of_speakers_enable_pro_contra_speech":            map[string]any{"type": "boolean"},
			"list_of_speakers_can_set_contribution_self":           map[string]any{"type": "boolean"},
			"list_of_speakers_speaker_note_for_everyone":           map[string]any{"type": "boolean"},
			"list_of_speakers_initially_closed":                    map[string]any{"type": "boolean"},
			"motions_default_workflow_id":      map[string]any{"type": "integer"},
			"motions_default_amendment_workflow_id": map[string]any{"type": "integer"},
			"motions_default_statute_amendment_workflow_id": map[string]any{"type": "integer"},
			"motions_preamble":                 map[string]any{"type": "string"},
			"motions_default_line_numbering":   map[string]any{"type": "string"},
			"motions_line_length":              map[string]any{"type": "integer"},
			"motions_reason_required":          map[string]any{"type": "boolean"},
			"motions_enable_text_on_projector": map[string]any{"type": "boolean"},
			"motions_enable_reason_on_projector": map[string]any{"type": "boolean"},
			"motions_enable_sidebox_on_projector": map[string]any{"type": "boolean"},
			"motions_enable_recommendation_on_projector": map[string]any{"type": "boolean"},
			"motions_show_referring_motions":   map[string]any{"type": "boolean"},
			"motions_show_sequential_number":   map[string]any{"type": "boolean"},
			"motions_recommendations_by":       map[string]any{"type": "string"},
			"motions_block_slide_columns":      map[string]any{"type": "integer"},
			"motions_statute_recommendations_by": map[string]any{"type": "string"},
			"motions_supporters_min_amount":    map[string]any{"type": "integer"},
			"motions_enable_editor":            map[string]any{"type": "boolean"},
			"motions_enable_working_group_speaker": map[string]any{"type": "boolean"},
			"motions_export_title":             map[string]any{"type": "string"},
			"motions_export_preamble":          map[string]any{"type": "string"},
			"motions_export_submitter_recommendation": map[string]any{"type": "boolean"},
			"motions_export_follow_recommendation":    map[string]any{"type": "boolean"},
			"assignment_poll_default_type":     map[string]any{"type": "string"},
			"assignment_poll_default_method":   map[string]any{"type": "string"},
			"assignment_poll_sort_poll_result_by_votes": map[string]any{"type": "boolean"},
			"assignment_poll_add_candidates_to_list_of_speakers": map[string]any{"type": "boolean"},
			"assignment_poll_enable_max_votes_per_option": map[string]any{"type": "boolean"},
			"users_enable_presence_view":       map[string]any{"type": "boolean"},
			"users_enable_vote_weight":         map[string]any{"type": "boolean"},
			"users_enable_vote_delegations":    map[string]any{"type": "boolean"},
			"users_allow_self_set_present":     map[string]any{"type": "boolean"},
			"users_pdf_welcometitle":           map[string]any{"type": "string"},
			"users_pdf_welcometext":            map[string]any{"type": "string"},
			"users_pdf_wlan_ssid":              map[string]any{"type": "string"},
			"users_pdf_wlan_password":          map[string]any{"type": "string"},
			"users_pdf_wlan_encryption":        map[string]any{"type": "string"},
			"users_email_sender":               map[string]any{"type": "string"},
			"users_email_replyto":              map[string]any{"type": "string"},
			"users_email_subject":              map[string]any{"type": "string"},
			"users_email_body":                 map[string]any{"type": "string"},
		},
		"required": []string{"id"},
	}

	action.Register(a)
}
